language: python
env:
  - DJANGO_VERSION=12
  - DJANGO_VERSION=13
  - DJANGO_VERSION=14
  - DJANGO_VERSION=15
  - DJANGO_VERSION=16
  - DJANGO_VERSION=17
  - DJANGO_VERSION=18
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
matrix:
    exclude:
        - env: DJANGO_VERSION=12
          python: "3.2"
        - env: DJANGO_VERSION=12
          python: "3.3"
        - env: DJANGO_VERSION=12
          python: "3.4"
        - env: DJANGO_VERSION=13
          python: "3.2"
        - env: DJANGO_VERSION=13
          python: "3.3"
        - env: DJANGO_VERSION=13
          python: "3.4"
        - env: DJANGO_VERSION=14
          python: "3.2"
        - env: DJANGO_VERSION=14
          python: "3.3"
        - env: DJANGO_VERSION=14
          python: "3.4"
# command to install dependencies
install:
  - pip install coveralls
  - pip install tox
# command to run tests
script: 
    - tox -e py${TRAVIS_PYTHON_VERSION/./}-django${DJANGO_VERSION}
after_success: coveralls
