language: python
env:
  - DJANGO_VERSION=1.2
  - DJANGO_VERSION=1.3
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
matrix:
    exclude:
        - env: DJANGO_VERSION=1.2
          python: "3.2"
        - env: DJANGO_VERSION=1.2
          python: "3.3"
        - env: DJANGO_VERSION=1.2
          python: "3.4"
        - env: DJANGO_VERSION=1.3
          python: "3.2"
        - env: DJANGO_VERSION=1.3
          python: "3.3"
        - env: DJANGO_VERSION=1.3
          python: "3.4"
        - env: DJANGO_VERSION=1.4
          python: "3.2"
        - env: DJANGO_VERSION=1.4
          python: "3.3"
        - env: DJANGO_VERSION=1.4
          python: "3.4"
# command to install dependencies
install:
  - pip install coveralls
  - pip install tox
# command to run tests
script: 
    - tox -e py${TRAVIS_PYTHON_VERSION/./}-django${DJANGO_VERSION}
after_success: coveralls
